import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50 text-slate-900`}>
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <header className="sticky top-0 z-40 w-full border-b border-slate-200 bg-white/70 backdrop-blur">
              <div className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between px-4">
                <Link href="/" className="flex items-center gap-2">
                  <span className="inline-flex h-8 w-8 items-center justify-center rounded-md bg-gradient-to-tr from-indigo-500 via-sky-500 to-emerald-400 text-xs font-bold text-white">AI</span>
                  <span className="text-sm font-semibold tracking-tight">AI File Assistant</span>
                </Link>
                <nav className="flex items-center gap-6">
                  <Link href="/" className="text-sm text-slate-700 hover:text-slate-900">Home</Link>
                  <Link href="/features" className="text-sm text-slate-700 hover:text-slate-900">Features</Link>
                  <Link href="/pricing" className="text-sm text-slate-700 hover:text-slate-900">Pricing</Link>
                  <Link href="/auth/login" className="text-sm text-slate-700 hover:text-slate-900">Login</Link>
                  <Link href="/auth/register" className="rounded-md bg-slate-900 px-3 py-1.5 text-sm text-white hover:bg-slate-800">Get Started</Link>
                </nav>
              </div>
            </header>
            <main className="flex-1 mx-auto w-full max-w-6xl px-4 py-10">{children}</main>
            <footer className="border-t border-slate-200 bg-white">
              <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-4 py-6 text-xs text-slate-600">
                <p>© {new Date().getFullYear()} AI File Assistant</p>
                <p>Built with Next.js & Tailwind CSS</p>
              </div>
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
