import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import Nav from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50 text-slate-900`}>
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <Nav />
            {/* AuthProvider exposes auth state app-wide so all pages/components can access it */}
            <main className="flex-1 mx-auto w-full max-w-6xl px-4 py-10">{children}</main>
            <footer className="border-t border-slate-200 bg-white">
              <div className="mx-auto flex w-full max-w-6xl flex-col items-start justify-between gap-1 px-4 py-6 text-xs text-slate-600 sm:flex-row">
                <p>© {new Date().getFullYear()} AI File Assistant.</p>
                <p>Built for organizing messy folders into a calm, searchable workspace.</p>
              </div>
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
